# remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

# collections:
#   # Define a collection named "tests", its documents reside in the "_tests" directory
#   legacy-code-projects:
#     permalink: "/:collection/:path/"
#     output: true

# just_the_docs:
#   # Define which collections are used in just-the-docs
#   collections:
#     # Reference the "tests" collection
#     legacy-code-projects:
#       # Give the collection a name
#       name: "Legacy Code Projects"
#       # Exclude the collection from the navigation
#       # Supports true or false (default)
#       nav_exclude: false
#       # Fold the collection in the navigation
#       # Supports true or false (default)
#       nav_fold: false
#       # Exclude the collection from the search
#       # Supports true or false (default)
#       search_exclude: false